salvation-request/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'requests#index'
  resources :requests

  get "bootstrap", to: "requests#bootstrap"

   

end

salvation-request/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

salvation-request/app/models/request.rb
class Request < ApplicationRecord
    
    belongs_to :user
end

salvation-request/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :requests
end

salvation-request/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        # pass the account information through the paramters
          devise_parameter_sanitizer.permit(:sign_up, keys: [ :name, :street_address, :city, :phone, :role])
          devise_parameter_sanitizer.permit(:account_update, keys: [ :name, :street_address, :city, :phone])
    end
end

salvation-request/app/controllers/requests_controller.rb
class RequestsController < ApplicationController
    before_action :authenticate_user! 
    before_action :find_request, except: [:index, :new, :create]
    before_action :user_name 


    def index
       
        # @requests = Request.all
        # @users = User.all
        if user_signed_in? && current_user.role == "admin"
          @requests = User.joins(:requests).select("requests.*","users.*")  
          

          
         
        else
          @requests = current_user.requests.all
        end
    end

    def show
        # @request = Request.find(params[:id])

        if @request.user != current_user
            flash[:notice] = 'Not allowed!'
            redirect_to requests_path
          end
    end


    def new
        
        @request = Request.new
    end

    def create 
        # @request = Request.new(request_params)
        # @request.save
        #  redirect_to @request

        @request = Request.new(request_params)

        @request.user = current_user
    
        if @request.save
          redirect_to requests_path
        else
          render 'new'
        end

    end

    def edit
        @request = Request.find(params[:id])
    end

    def update
        request = Request.find(params[:id])
        request.update(request_params)
        
        redirect_to requests_path

    end

    def edit
        @request = Request.find(params[:id])
    end

    def update
        request = Request.find(params[:id])
        request.update(request_params)
        
        redirect_to requests_path

    end

    def destroy
        Request.find(params[:id]).destroy
      
        redirect_to requests_path
      end

    private
    def request_params
         params.require(:request).permit(:request_type, :request_description, :request_status)
    end

    def find_request
        @request = Request.find(params[:id])
        
      end

      def user_name 
        @user = User.find_by id:current_user
      end
end

salvation-request/app/helpers/application_helper.rb
module ApplicationHelper
end

salvation-request/app/helpers/requests_helper.rb
module RequestsHelper
end

salvation-request/app/views/layouts/_nav.html.erb
 <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
     <a class="navbar-brand" href="/">SalvationRequest</a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
     </button>
     <div class="collapse navbar-collapse" id="navbarCollapse">
         <ul class="navbar-nav mr-auto">
             <li class="nav-item active">
                 <%= link_to('Home', requests_path, class: 'nav-item nav-link active') %>
             </li>
             <% if  user_signed_in? && current_user.role == "normal_user" %>
             <li class="nav-item ">
                 <%= link_to('New Request', new_request_path, class: 'nav-item nav-link active') %>
             </li>
             <%end%>

         </ul>


         <ul class="navbar-nav ml-auto">

             <% if user_signed_in? %>
             <li class="nav-item dropdown active ">
                 <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                     <i class="fas fa-user-circle"></i> <%= @user.name%>
                 </a>
                 <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                     <a class="dropdown-item" data-method="get" href="/users/edit">Edit Account</a>
                     <div class="dropdown-divider"></div>
                     <a class="dropdown-item" data-confirm="Are you sure you want to logout ?" data-method="delete" href="/users/sign_out">Logout </a>
                 </div>
             </li>
             <% else %>
             <li class="nav-item dropdown active">
                 <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                     Sign up / Signin
                 </a>
                 <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                     <a class="dropdown-item" data-method="get" href="/users/sign_in">Sign in</a>

                     <div class=" dropdown-divider"></div>
                     <a class=" dropdown-item" data-method="get" href="/users/sign_up">Sign up</a>
                 </div>
             </li>
             <% end %>
         </ul>

     </div>

 </nav>

salvation-request/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>

    <title>SalvationRequest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<meta name="viewport" content="width=device-width, initial-scale=1">



    <%# <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/7bd0b21df5.js" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css2?family=Tajawal:wght@400;800&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>

</head>

<body>
    <%= render 'layouts/nav' %>
    <header>

        <ul>





        </ul>
    </header>


    <p class="notice"><%= notice %></p>



    <p class="alert  "><%= alert %></p>


    <%= yield %>
</body>


</html>

salvation-request/app/views/requests/_form.html.erb
 <%= form_with model: @request, local: true do |form| %>




 <p>
     Request Type
     <%= form.select(:request_type, [['Food Support'], ['Babysitting  Service']]) %>
 </p>

 <p>
     Description:
     <%= form.text_area :request_description %>
 </p>

 <% if current_user.role == "admin"%>
 <p>
     Request Type
     <%= form.select(:request_status, [['New'], ['In-Progress'], ['Completed']]) %>
 </p>
 <%end%>



 <%= form.submit %>
 <% end %>

salvation-request/app/views/requests/edit.html.erb
<style>
    h1 {
        font-size: 1.4em;

    }
</style>

<div class="d-flex justify-content-center">
    <div class="card col-10 col-md-4 ">
        <div class="card-body">

            <div class="container">
                <div class="row justify-content-center" style="text-align:center;">

                    <div class="col-4">

                        <h1> Edit <h1>

                                <%= render partial: 'form', locals: { request: @request } %>


                    </div>

                </div>

            </div>



        </div>
    </div>
</div>

salvation-request/app/views/requests/index.html.erb
<div class="d-flex justify-content-center">
    <div class="card col-10">
        <div class="card-body">
            <div class="container">
                <div class="row">

                    <div class="col-12">
                        <%# 2 of 3 (wider) %>
                        <%# content  %>

                        <h2 class="text-center">Request List <i class="fas fa-clipboard-list"></i> </h2>

                        <%# Add a table for the request  %>


                        <table class="table">
                            <% if current_user.role == "normal_user"%>
                            <a class="btn btn-dark" id="addbtn" data-method="get" href="/requests/new"><i class="fas fa-plus-square fa-1x"></i> Add a request</a>
                            <% end%>
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">id</th>
                                    <th scope="col">Type</th>
                                    <%if user_signed_in? && current_user.role == "admin"%>
                                    <th scope="col">Created By</th>
                                    <th scope="col">Phone</th>
                                    <%end%>
                                    <th scope="col">City</th>
                                    <th scope="col">Status</th>
                                    <th scope="col"></th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>

                            <%# All the requests  %>
                            <tbody>
                                <% @requests.each do |request|%>

                                <tr>
                                    <td>
                                        <%=  request.id   %>
                                    </td>
                                    <td>
                                        <%=   request.request_type   %>
                                    </td>
                                    <%if user_signed_in? && current_user.role == "admin"%>
                                    <td>
                                        <%=  request.name    %>
                                    </td>
                                    <td>
                                        <%=  request.phone    %>
                                    </td>
                                    <% end%>
                                    <td>
                                        <%=  @user.city  %>
                                    </td>
                                    <td>
                                        <%=  request.request_status  %>
                                    </td>
                                    <td>

                                        <a class="btn  flex-row-reverse" id="removebtn" data-confirm="Are you sure you want to delete" data-method="delete" href="/requests/<%=request.id%>"><i class="fas fa-trash-alt"></i> </a>
                                        <% if current_user.role == "admin"%>
                                        <a class="btn   flex-row-reverse" id="editbtn" data-method="get" href="/requests/<%=request.id%>/edit"><i class="far fa-edit"></i></a>
                                        <% end%>
                                    </td>

                                </tr>

                                <% end %>
                                </tr>
                            </tbody>
                        </table>


                    </div>

                </div>

            </div>



        </div>
    </div>
</div>

salvation-request/app/views/requests/new.html.erb
<div class="d-flex justify-content-center">
    <div class="card col-11 col-md-4">
        <div class="card-body">

            <div class="container">
                <div class="row justify-content-center" style="text-align:center;">

                    <div class="col-6">

                        <h1> New </h1>

                        <%= render partial: 'form', locals: { request: @request } %>

                    </div>

                </div>

            </div>



        </div>
    </div>
</div>

salvation-request/app/views/requests/show.html.erb
<div class="d-flex justify-content-center">
    <div class="card col-11 col-md-4">
        <div class="card-body">

            <div class="container">
                <div class="row justify-content-center" style="text-align:center;">



                    <h1> Show all requests <h1>

                            <ul>

                                <li> Type: <%= @request.request_type%> </li>
                                <li> Description: <%= @request.request_description%></li>
                                <li> Status: <%= @request.request_status%></li>

                                <% if current_user.role == "admin"%>
                                <li><%= link_to 'Edit', edit_request_path %></li>
                                <% end %>

                            </ul>




                </div>

            </div>



        </div>
    </div>
</div>